#!/usr/bin/env python3
"""r2_ordering_constraint.py -- Ordering Constraint & Geometric Structure Analysis.

CONTEXT:
  In the Collatz cycle problem, the Horner chain uses exponents b_1 < b_2 < ... < b_{k-1}
  (strictly increasing). The chain processes them in DECREASING order:
      c_0 = 0
      c_{j+1} = 3*c_j + 2^{b_{k-1-j}} mod p     for j = 0, ..., k-2

  The multipliers 2^{b_i} mod p lie on the orbit of 2 in the cyclic group (Z/pZ)*.
  The key question: does the strict ordering constraint create any exploitable bias
  that makes corrSum = 0 mod p less likely than the naive 1/p prediction?

RESEARCH QUESTIONS:
  Q1. GEOMETRIC STRUCTURE (Section S2):
      For each prime p | d(k), compute ord_p(2) and the coverage ratio ord_p(2)/(p-1).
      How much of (Z/pZ)* is reached by powers of 2?

  Q2. ORDERING BIAS (Section S3):
      The exponents are decreasing in the Horner chain. The multipliers are
      2^{b_{k-1}}, 2^{b_{k-2}}, ..., 2^{b_1}. Does P(corrSum=0) differ from 1/p?

  Q3. CONSECUTIVE RATIO ANALYSIS (Section S4):
      Consecutive multiplier ratios are 2^{-gap} where gap >= 1. Does the constraint
      that all ratios are negative powers of 2 reduce randomness?

  Q4. SUBGROUP STRUCTURE (Section S5):
      When ord_p(2) < p-1, values 2^b lie in a proper subgroup of (Z/pZ)*.
      The corrSum involves both powers of 2 AND powers of 3 (from Horner coefficients).
      The relevant group is <2, 3> = subgroup generated by 2 and 3 in (Z/pZ)*.
      If <2, 3> = (Z/pZ)*, then corrSum can reach all residues mod p.

  Q5. KEY QUESTION (Section S6):
      Does the ordering constraint create any exploitable bias making
      corrSum = 0 mod p less likely?

METHODOLOGY:
  - Exact enumeration for k = 7..12 (feasible)
  - Random sampling (200K samples) for k = 13..20 (infeasible for exact)
  - All results compared against the null hypothesis P(corrSum=0) = 1/p

Author: Eric Merle (assisted by Claude)
Date:   March 2026
"""

import math
import hashlib
import json
import sys
import time
from itertools import combinations, permutations
from collections import defaultdict, Counter
import random

# Reproducible randomness
RNG_SEED = 20260308
RNG = random.Random(RNG_SEED)


# ============================================================================
# S0. MATHEMATICAL PRIMITIVES
# ============================================================================

def S_of_k(k):
    """S(k) = ceil(k * log2(3))."""
    return math.ceil(k * math.log2(3))


def d_of_k(k):
    """d(k) = 2^S - 3^k."""
    S = S_of_k(k)
    return (1 << S) - 3**k


def prime_factors(n):
    """Return sorted list of distinct prime factors of |n|."""
    n = abs(n)
    if n <= 1:
        return []
    factors = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            factors.append(d)
            while n % d == 0:
                n //= d
        d += 1
    if n > 1:
        factors.append(n)
    return sorted(factors)


def multiplicative_order(base, p):
    """Multiplicative order of base mod p. Returns 0 if gcd(base,p) != 1."""
    if math.gcd(base, p) != 1:
        return 0
    r = 1
    for m in range(1, p):
        r = (r * base) % p
        if r == 1:
            return m
    return p - 1


def modinv(a, p):
    """Modular inverse of a mod p (p prime)."""
    return pow(a, p - 2, p)


def is_prime(n):
    """Primality test."""
    if n < 2:
        return False
    if n < 4:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True


# ============================================================================
# S1. HORNER CHAIN COMPUTATIONS
# ============================================================================

def horner_chain_ordered(subset_sorted, k, p):
    """Compute Horner chain in the STANDARD decreasing order.

    Elements are processed in order b_{k-1}, b_{k-2}, ..., b_1 (decreasing).
    Transition: c -> 3*c + 2^a mod p.

    Parameters:
        subset_sorted: tuple/list of (k-1) elements sorted ASCENDING
        k: cycle length
        p: prime modulus

    Returns:
        c_{k-1}: final value mod p (= corrSum mod p)
    """
    km1 = k - 1
    c = 0
    for j in range(km1):
        a = subset_sorted[km1 - 1 - j]
        c = (3 * c + pow(2, a, p)) % p
    return c


def horner_chain_full(subset_sorted, k, p):
    """Compute FULL Horner chain c_0, ..., c_{k-1} mod p (for detailed analysis).

    Returns list [c_0, c_1, ..., c_{k-1}].
    """
    km1 = k - 1
    chain = [0]
    for j in range(km1):
        a = subset_sorted[km1 - 1 - j]
        c_next = (3 * chain[-1] + pow(2, a, p)) % p
        chain.append(c_next)
    return chain


def horner_chain_arbitrary_order(elements_in_order, p):
    """Compute Horner chain with elements processed in given order.

    Returns c_final mod p.
    """
    c = 0
    for a in elements_in_order:
        c = (3 * c + pow(2, a, p)) % p
    return c


def corrsum_direct(subset_sorted, k, p):
    """Compute corrSum directly: sum_{i=1}^{k-1} 3^{i-1} * 2^{b_i} mod p.

    This matches the backward Horner chain:
      c_{k-1} = sum_{i=1}^{k-1} 3^{i-1} * 2^{b_i} mod p
    """
    km1 = k - 1
    s = 0
    for i in range(km1):
        s = (s + pow(3, i, p) * pow(2, subset_sorted[i], p)) % p
    return s


# ============================================================================
# S_SELF. SELF-TESTS
# ============================================================================

def self_test():
    """Comprehensive self-tests for all core functions."""
    print("=" * 72)
    print("  SELF-TESTS")
    print("=" * 72)
    print()
    ok = True
    n_tests = 0

    # Test 1: S_of_k and d_of_k
    cases_sd = {
        3: (5, 5), 4: (7, 47), 5: (8, 13), 6: (10, 295),
        7: (12, 1909), 8: (13, 1631), 9: (15, 13085),
        10: (16, 6487), 11: (18, 84997), 12: (20, 517135),
    }
    for k, (exp_S, exp_d) in cases_sd.items():
        S = S_of_k(k)
        d = d_of_k(k)
        assert S == exp_S, f"S({k}) = {S}, expected {exp_S}"
        assert d == exp_d, f"d({k}) = {d}, expected {exp_d}"
        n_tests += 1
    print(f"  [PASS] S(k), d(k) correct ({n_tests} cases)")

    # Test 2: Prime factorization
    test_pf = {
        5: [5], 13: [13], 47: [47], 295: [5, 59],
        1909: [23, 83], 1631: [7, 233], 6487: [13, 499],
    }
    for n, expected in test_pf.items():
        assert prime_factors(n) == expected, f"prime_factors({n}) = {prime_factors(n)}"
        n_tests += 1
    print(f"  [PASS] Prime factorization ({n_tests} total)")

    # Test 3: Multiplicative order
    test_ord = [
        (2, 5, 4), (2, 7, 3), (2, 13, 12), (3, 13, 3),
        (2, 17, 8), (2, 23, 11), (2, 83, 82), (2, 59, 58),
    ]
    for base, p, exp_ord in test_ord:
        o = multiplicative_order(base, p)
        assert o == exp_ord, f"ord_{p}({base}) = {o}, expected {exp_ord}"
        n_tests += 1
    print(f"  [PASS] Multiplicative orders ({n_tests} total)")

    # Test 4: modinv
    for p in [5, 7, 11, 13, 17, 23, 59, 83]:
        inv = modinv(2, p)
        assert (2 * inv) % p == 1, f"modinv(2, {p}) failed"
        n_tests += 1
    print(f"  [PASS] Modular inverse ({n_tests} total)")

    # Test 5: Horner chain vs direct corrSum
    for k in [3, 4, 5, 6]:
        S = S_of_k(k)
        d = d_of_k(k)
        primes = [p for p in prime_factors(d) if p <= 200]
        for p in primes:
            for subset in combinations(range(1, S), k - 1):
                c_horner = horner_chain_ordered(subset, k, p)
                c_direct = corrsum_direct(subset, k, p)
                assert c_horner == c_direct, (
                    f"k={k}, p={p}, A={subset}: horner={c_horner}, direct={c_direct}")
                n_tests += 1
    print(f"  [PASS] Horner = direct corrSum ({n_tests} total)")

    # Test 6: Full chain matches final value
    for k in [3, 5, 7]:
        S = S_of_k(k)
        d = d_of_k(k)
        for p in prime_factors(d):
            if p > 200:
                continue
            count = 0
            for subset in combinations(range(1, S), k - 1):
                chain = horner_chain_full(subset, k, p)
                final = horner_chain_ordered(subset, k, p)
                assert chain[-1] == final
                assert chain[0] == 0
                count += 1
                if count >= 200:
                    break
            n_tests += 1
    print(f"  [PASS] Full chain consistency ({n_tests} total)")

    # Test 7: Arbitrary order with decreasing = standard
    k, p = 5, 13
    S = S_of_k(k)
    count = 0
    for subset in combinations(range(1, S), k - 1):
        standard = horner_chain_ordered(subset, k, p)
        decreasing = [subset[k - 2 - j] for j in range(k - 1)]
        arbitrary = horner_chain_arbitrary_order(decreasing, p)
        assert standard == arbitrary
        count += 1
    n_tests += 1
    print(f"  [PASS] Arbitrary-decreasing = standard ({count} checks, {n_tests} total)")

    # Test 8: Verify our backward Horner convention is internally consistent
    # Backward Horner for k=3: corrSum = sum 3^{i} * 2^{subset[i]}
    # = 3^0 * 2^{b_1} + 3^1 * 2^{b_2} (i.e., smallest gets weight 1, largest weight 3)
    #
    # NOTE: Forward Horner (as in tz_arc_decomposition.py) computes a DIFFERENT
    # linear form: sum 3^{k-1-j} * 2^{b_j}. For k=3: 3^1*2^{b_1} + 3^0*2^{b_2}.
    # The two forms are "reversed" polynomials and give DIFFERENT solution counts
    # mod a given p (though both are valid formulations of the cycle equation).
    # Our analysis is valid regardless of convention since we only compare
    # P(corrSum=0) to 1/p, and the 1/p heuristic applies to both forms.

    # Verify backward Horner for k=3, p=5:
    # {1,4}: corrSum = 2^1 + 3*2^4 = 2+48 = 50 = 0 mod 5 -> YES
    c = horner_chain_ordered((1, 4), 3, 5)
    assert c == 0, f"Expected corrSum({(1,4)})=0 mod 5, got {c}"

    # Count backward solutions for k=3, p=5
    N_back = 0
    for subset in combinations(range(1, 5), 2):
        if horner_chain_ordered(subset, 3, 5) == 0:
            N_back += 1
    # C(4,2) = 6 subsets, ~6/5 = 1.2 expected, so 1 is reasonable
    assert N_back >= 1, f"Expected at least 1 solution, got {N_back}"
    n_tests += 1
    print(f"  [PASS] Backward Horner k=3: {N_back}/6 solutions ({n_tests} total)")

    # Test 9: Transient Zero Property for k=3..8
    tz_violations = 0
    for k in range(3, 9):
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 0:
            continue
        for p in prime_factors(d):
            if p > 200:
                continue
            for subset in combinations(range(1, S), k - 1):
                chain = horner_chain_full(subset, k, p)
                for j in range(len(chain) - 1):
                    if chain[j] == 0 and chain[j + 1] == 0:
                        tz_violations += 1
    assert tz_violations == 0, f"Transient Zero violations: {tz_violations}"
    n_tests += 1
    print(f"  [PASS] Transient Zero Property k=3..8 ({n_tests} total)")

    # Test 10: Ordering constraint - exponents processed in decreasing order
    k = 7
    S = S_of_k(k)
    subset = [1, 3, 5, 7, 9, 11]  # k-1 = 6 elements
    exps_processed = [subset[k - 2 - j] for j in range(k - 1)]
    assert exps_processed == [11, 9, 7, 5, 3, 1], f"Wrong order: {exps_processed}"
    for i in range(len(exps_processed) - 1):
        assert exps_processed[i] > exps_processed[i + 1]
    n_tests += 1
    print(f"  [PASS] Decreasing order verification ({n_tests} total)")

    # Test 11: Coverage ratio computation
    assert multiplicative_order(2, 5) == 4  # ord=4, p-1=4, coverage=1.0
    assert multiplicative_order(2, 7) == 3  # ord=3, p-1=6, coverage=0.5
    assert multiplicative_order(2, 13) == 12  # 2 is prim root mod 13
    n_tests += 3
    print(f"  [PASS] Coverage ratios ({n_tests} total)")

    # Test 12: Subgroup <2,3> via lcm formula
    # In a cyclic group, |<2,3>| = lcm(ord(2), ord(3))
    # Verify against brute-force for small primes
    for p in [5, 7, 11, 13, 23, 59, 83]:
        o2 = multiplicative_order(2, p)
        o3 = multiplicative_order(3, p)
        lcm_val = math.lcm(o2, o3)
        # Brute-force verification
        gen = set()
        for a in range(o2):
            for b in range(o3):
                gen.add(pow(2, a, p) * pow(3, b, p) % p)
        gen.discard(0)
        assert len(gen) == lcm_val, (
            f"p={p}: brute-force |<2,3>|={len(gen)}, lcm={lcm_val}")
        n_tests += 1
    # Specific check: p=7, ord2=3, ord3=6 -> lcm=6 = p-1 (full group)
    assert math.lcm(3, 6) == 6 == 7 - 1
    # p=23, ord2=11, ord3=11 -> lcm=11, p-1=22 (proper subgroup, index 2)
    assert math.lcm(11, 11) == 11
    assert 11 < 22  # proper subgroup
    n_tests += 2
    print(f"  [PASS] Subgroup <2,3> via lcm formula ({n_tests} total)")

    print()
    print(f"  ALL {n_tests} SELF-TESTS PASS")
    print()
    return True


# ============================================================================
# S2. GEOMETRIC STRUCTURE: <2> mod p
# ============================================================================

def analyze_geometric_structure(k_range):
    """For each prime p | d(k), analyze the cyclic subgroup <2> mod p.

    Computes:
      - ord_p(2) : multiplicative order of 2 mod p
      - Coverage : ord_p(2) / (p-1), fraction of (Z/pZ)* covered
      - Whether 2 is a primitive root mod p
    """
    print("=" * 72)
    print("  S2. GEOMETRIC STRUCTURE OF <2> MOD p")
    print("=" * 72)
    print()
    print("  For each k in {7,...,20} and each prime p | d(k):")
    print("    ord_p(2) = multiplicative order of 2 in (Z/pZ)*")
    print("    coverage = ord_p(2) / (p-1)")
    print("    prim.root = whether 2 generates all of (Z/pZ)*")
    print()

    results = {}
    all_primes_seen = set()
    primitive_root_count = 0
    total_prime_count = 0

    hdr = (f"  {'k':>3} {'S':>4} {'d(k)':>20} {'p':>14} {'ord_p(2)':>10} "
           f"{'coverage':>10} {'prim':>5}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    for k in k_range:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue
        primes = prime_factors(d)

        for p in primes:
            if p < 3:
                continue
            all_primes_seen.add(p)
            total_prime_count += 1

            ord_2 = multiplicative_order(2, p)
            coverage = ord_2 / (p - 1) if p > 1 else 0
            prim = (ord_2 == p - 1)
            if prim:
                primitive_root_count += 1

            results[(k, p)] = {
                'S': S, 'd': d, 'ord_2': ord_2,
                'coverage': coverage, 'primitive_root': prim
            }

            prim_str = "YES" if prim else "no"
            print(f"  {k:>3} {S:>4} {d:>20} {p:>14} {ord_2:>10} "
                  f"{coverage:>10.4f} {prim_str:>5}")

    print()
    print(f"  Summary: {len(all_primes_seen)} distinct primes, k = {min(k_range)}..{max(k_range)}")
    print(f"    Primitive root count: {primitive_root_count}/{total_prime_count} "
          f"({100*primitive_root_count/max(total_prime_count,1):.1f}%)")

    coverages = [r['coverage'] for r in results.values()]
    if coverages:
        print(f"    Coverage: min={min(coverages):.4f}, max={max(coverages):.4f}, "
              f"mean={sum(coverages)/len(coverages):.4f}")
        full_cov = sum(1 for c in coverages if abs(c - 1.0) < 1e-10)
        print(f"    Full coverage (prim. root): {full_cov}/{len(coverages)}")

    print()
    return results


# ============================================================================
# S3. ORDERING BIAS: P(corrSum=0) vs 1/p
# ============================================================================

def analyze_ordering_bias(k_range_exact, k_range_sample, n_samples=200000):
    """Compare P(corrSum=0) to 1/p for each (k, p) pair.

    Exact enumeration for small k, random sampling for large k.

    Returns list of result dicts.
    """
    print("=" * 72)
    print("  S3. ORDERING BIAS: P(corrSum=0) vs 1/p")
    print("=" * 72)
    print()
    print("  P(corrSum=0) should equal 1/p if the ordering has no effect.")
    print("  We compute the exact ratio P(corrSum=0) / (1/p) for k = 7..20.")
    print("  (* = exact enumeration, others = sampling with 200K samples)")
    print()

    rng = random.Random(RNG_SEED)

    results = []

    hdr = (f"  {'k':>3} {'p':>12} {'ord(2)':>8} {'N':>10} {'#sol':>10} "
           f"{'P(0)':>12} {'1/p':>12} {'ratio':>8} {'95% CI':>22} {'':>2}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    all_k = sorted(set(k_range_exact) | set(k_range_sample))

    for k in all_k:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue

        n_total = math.comb(S - 1, k - 1)
        primes = prime_factors(d)

        for p in primes:
            if p < 3:
                continue

            ord_2 = multiplicative_order(2, p)
            use_exact = (k in k_range_exact) and (n_total <= 500000)

            if use_exact:
                sol_count = 0
                for subset in combinations(range(1, S), k - 1):
                    if horner_chain_ordered(subset, k, p) == 0:
                        sol_count += 1
                N = n_total
                P_zero = sol_count / N
                ci_low, ci_high = P_zero, P_zero
                tag = "*"
            else:
                sol_count = 0
                pool = list(range(1, S))
                N = n_samples
                for _ in range(N):
                    subset = sorted(rng.sample(pool, k - 1))
                    if horner_chain_ordered(subset, k, p) == 0:
                        sol_count += 1
                P_zero = sol_count / N
                # Wilson confidence interval
                z = 1.96
                phat = P_zero
                denom = 1 + z**2 / N
                center = (phat + z**2 / (2*N)) / denom
                margin = z * math.sqrt(phat*(1-phat)/N + z**2/(4*N**2)) / denom
                ci_low = max(0, center - margin)
                ci_high = min(1, center + margin)
                tag = " "

            inv_p = 1.0 / p
            ratio = P_zero / inv_p if inv_p > 0 else float('inf')

            results.append({
                'k': k, 'p': p, 'ord_2': ord_2,
                'N': N, 'sol_count': sol_count,
                'P_zero': P_zero, 'inv_p': inv_p, 'ratio': ratio,
                'ci_low': ci_low, 'ci_high': ci_high,
                'method': 'exact' if tag == '*' else 'sample',
            })

            ci_str = (f"[{ci_low:.6f},{ci_high:.6f}]"
                      if tag != '*' else f"{'(exact)':>22}")
            print(f"  {k:>3} {p:>12} {ord_2:>8} {N:>10} {sol_count:>10} "
                  f"{P_zero:>12.6f} {inv_p:>12.6f} {ratio:>8.4f} "
                  f"{ci_str:>22} {tag:>2}")

    # Summary
    if results:
        ratios = [r['ratio'] for r in results]
        print()
        print("  Summary of P(corrSum=0) / (1/p):")
        print(f"    Mean ratio  : {sum(ratios)/len(ratios):.6f}")
        stdev = (sum((r - sum(ratios)/len(ratios))**2 for r in ratios) / len(ratios))**0.5
        print(f"    Std ratio   : {stdev:.6f}")
        print(f"    Range       : [{min(ratios):.6f}, {max(ratios):.6f}]")

        # t-test: is mean ratio significantly different from 1?
        if len(ratios) > 1:
            mean_r = sum(ratios) / len(ratios)
            se = stdev / len(ratios)**0.5
            t_stat = (mean_r - 1.0) / se if se > 0 else 0
            print(f"    t-statistic : {t_stat:.3f} (H0: ratio = 1)")
            sig = abs(t_stat) > 2.0
            print(f"    Significant : {'YES' if sig else 'NO'} at 95% level")

        # Check: is 1/p within CI for sampled cases?
        sampled = [r for r in results if r['method'] == 'sample']
        if sampled:
            in_ci = sum(1 for r in sampled if r['ci_low'] <= r['inv_p'] <= r['ci_high'])
            print(f"    1/p in 95% CI: {in_ci}/{len(sampled)} sampled cases")

        neg_count = sum(1 for r in ratios if r < 1.0)
        print(f"    Ratio < 1 (fewer solutions than 1/p): {neg_count}/{len(ratios)}")

        # Filtered summary: exclude cases where expected count N/p < 5
        # (standard rule for reliable chi-squared / ratio statistics)
        well_sampled = [r for r in results if r['N'] * r['inv_p'] >= 5]
        if well_sampled and len(well_sampled) < len(results):
            ws_ratios = [r['ratio'] for r in well_sampled]
            ws_mean = sum(ws_ratios) / len(ws_ratios)
            ws_std = (sum((r - ws_mean)**2 for r in ws_ratios) / len(ws_ratios))**0.5
            print()
            print(f"  Filtered summary (N/p >= 5, {len(well_sampled)}/{len(results)} cases):")
            print(f"    Mean ratio  : {ws_mean:.6f}")
            print(f"    Std ratio   : {ws_std:.6f}")
            print(f"    Range       : [{min(ws_ratios):.6f}, {max(ws_ratios):.6f}]")
            if len(ws_ratios) > 1:
                ws_se = ws_std / len(ws_ratios)**0.5
                ws_t = (ws_mean - 1.0) / ws_se if ws_se > 0 else 0
                print(f"    t-statistic : {ws_t:.3f}")
                print(f"    Significant : {'YES' if abs(ws_t) > 2.0 else 'NO'} at 95% level")
            print(f"    NOTE: Excludes {len(results)-len(well_sampled)} cases where")
            print(f"    expected count N/p < 5 (unreliable for ratio estimation)")

    print()
    return results


# ============================================================================
# S4. CONSECUTIVE RATIO ANALYSIS
# ============================================================================

def analyze_consecutive_ratios(k_range_detail):
    """Analyze the consecutive ratios in the Horner chain.

    Consecutive multipliers: 2^{b_{k-1-j}} then 2^{b_{k-2-j}}.
    Ratio = 2^{b_{k-2-j}} / 2^{b_{k-1-j}} = 2^{-(gap)} mod p, gap >= 1.

    KEY QUESTION: Does the constraint that all ratios are negative powers of 2
    (with gap >= 1) reduce randomness compared to unconstrained sampling?
    """
    print("=" * 72)
    print("  S4. CONSECUTIVE RATIO ANALYSIS")
    print("=" * 72)
    print()
    print("  In the Horner chain (decreasing order), consecutive multiplier")
    print("  ratios are 2^{-gap} mod p where gap = b_{i+1} - b_i >= 1.")
    print("  We analyze how constrained these ratios are.")
    print()

    for k in k_range_detail:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue

        n_subsets = math.comb(S - 1, k - 1)
        primes = prime_factors(d)

        for p in primes:
            if p < 3 or n_subsets > 100000:
                continue

            ord_2 = multiplicative_order(2, p)

            # Possible ratio values: 2^{-g} for g = 1, ..., S-2
            possible_ratios = set()
            for g in range(1, S):
                possible_ratios.add(pow(modinv(2, p), g, p))
            coverage_ratio = len(possible_ratios) / (p - 1)

            # Collect gap distributions for corrSum=0 vs !=0
            gap_counter_zero = Counter()
            gap_counter_nonzero = Counter()
            n_zero = 0
            n_total = 0

            for subset in combinations(range(1, S), k - 1):
                n_total += 1
                c = horner_chain_ordered(subset, k, p)

                # Inner gaps
                inner_gaps = [subset[i+1] - subset[i] for i in range(len(subset)-1)]

                if c == 0:
                    n_zero += 1
                    for g in inner_gaps:
                        gap_counter_zero[g] += 1
                else:
                    for g in inner_gaps:
                        gap_counter_nonzero[g] += 1

            print(f"  k={k}, p={p}, ord_p(2)={ord_2}, S={S}")
            print(f"    Possible ratios (gaps 1..{S-1}): {len(possible_ratios)}/{p-1} "
                  f"of (Z/pZ)* ({coverage_ratio:.2%})")
            print(f"    Solutions: {n_zero}/{n_total} "
                  f"(P(0)={n_zero/n_total:.6f}, 1/p={1/p:.6f})")

            # Compare gap distributions
            total_g0 = sum(gap_counter_zero.values())
            total_gnz = sum(gap_counter_nonzero.values())
            if total_g0 > 0 and total_gnz > 0:
                # Mean gap
                mean_g0 = sum(g * c for g, c in gap_counter_zero.items()) / total_g0
                mean_gnz = sum(g * c for g, c in gap_counter_nonzero.items()) / total_gnz
                print(f"    Mean gap (sol):   {mean_g0:.4f}")
                print(f"    Mean gap (non):   {mean_gnz:.4f}")
                print(f"    Gap delta:        {mean_g0 - mean_gnz:+.4f}")

                # Show distribution
                all_gaps_set = sorted(set(gap_counter_zero.keys()) |
                                      set(gap_counter_nonzero.keys()))
                print(f"    {'gap':>6} {'freq(sol)':>10} {'freq(non)':>10} {'ratio':>8}")
                for g in all_gaps_set[:8]:
                    f0 = gap_counter_zero.get(g, 0) / total_g0
                    fnz = gap_counter_nonzero.get(g, 0) / total_gnz
                    r = f0 / fnz if fnz > 0 else float('inf')
                    r_s = f"{r:.4f}" if r != float('inf') else "inf"
                    print(f"    {g:>6} {f0:>10.4f} {fnz:>10.4f} {r_s:>8}")

            print()

    return


# ============================================================================
# S5. SUBGROUP STRUCTURE ANALYSIS
# ============================================================================

def analyze_subgroup_structure(k_range):
    """Analyze <2, 3> mod p for each prime p | d(k).

    When ord_p(2) < p-1, the values 2^b lie in a proper subgroup H.
    But corrSum involves BOTH 2^{b_j} AND 3^{j} coefficients.
    The relevant algebraic structure is the subgroup <2, 3> of (Z/pZ)*.
    If <2, 3> = (Z/pZ)*, corrSum can reach all residues mod p.
    """
    print("=" * 72)
    print("  S5. SUBGROUP STRUCTURE: <2, 3> MOD p")
    print("=" * 72)
    print()
    print("  corrSum = sum 3^{j-1} * 2^{b_j}. The terms involve both powers")
    print("  of 2 (from exponents) and powers of 3 (from Horner coefficients).")
    print("  If <2,3> is a proper subgroup of (Z/pZ)*, corrSum is restricted")
    print("  to cosets of this subgroup, potentially affecting P(corrSum=0).")
    print()

    hdr = (f"  {'k':>3} {'p':>12} {'ord_p(2)':>10} {'ord_p(3)':>10} "
           f"{'|<2,3>|':>10} {'p-1':>10} {'full?':>6} {'index':>6}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    subgroup_data = []

    for k in k_range:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue

        for p in prime_factors(d):
            if p < 3:
                continue

            ord_2 = multiplicative_order(2, p)
            ord_3 = multiplicative_order(3, p)

            # In the cyclic group (Z/pZ)*, the subgroup generated by 2 and 3
            # has order lcm(ord_p(2), ord_p(3)). This follows from the fact
            # that every subgroup of a cyclic group is cyclic, and the
            # subgroup generated by subgroups of orders d1 and d2 has
            # order lcm(d1, d2).
            size_23 = math.lcm(ord_2, ord_3)
            is_full = (size_23 == p - 1)
            index = (p - 1) // size_23 if size_23 > 0 else 0

            subgroup_data.append({
                'k': k, 'p': p, 'ord_2': ord_2, 'ord_3': ord_3,
                'size_23': size_23, 'is_full': is_full, 'index': index
            })

            full_str = "YES" if is_full else "NO"
            print(f"  {k:>3} {p:>12} {ord_2:>10} {ord_3:>10} "
                  f"{size_23:>10} {p-1:>10} {full_str:>6} {index:>6}")

    # Summary
    if subgroup_data:
        full_count = sum(1 for s in subgroup_data if s['is_full'])
        total = len(subgroup_data)
        print()
        print(f"  Summary: <2,3> = (Z/pZ)* for {full_count}/{total} primes "
              f"({100*full_count/max(total,1):.1f}%)")
        if full_count == total:
            print("  RESULT: corrSum can reach ALL residues mod p for EVERY prime.")
            print("  The subgroup structure does NOT restrict the range of corrSum.")
        else:
            non_full = [s for s in subgroup_data if not s['is_full']]
            print(f"  WARNING: {len(non_full)} primes have <2,3> as proper subgroup:")
            for s in non_full:
                print(f"    k={s['k']}, p={s['p']}: |<2,3>|={s['size_23']}, "
                      f"index={(s['p']-1)//s['size_23']}")
                # For these, P(corrSum=0) could differ from 1/p
                # If 0 is not in the image of corrSum, then P=0 instead of 1/p!
                # But 0 is the identity element and is always reachable (empty sum).
                # The question is whether corrSum can equal 0 when it's a sum
                # of terms from a proper coset.

    print()
    return subgroup_data


# ============================================================================
# S6. ORDERED vs SHUFFLED COMPARISON
# ============================================================================

def compare_ordered_vs_shuffled(k_range_detail, n_shuffles=50):
    """Compare P(corrSum=0) for ordered vs randomly shuffled processing.

    For each subset, the corrSum depends on the ORDER in which elements
    are processed. The standard order is decreasing; shuffled is random.

    If ordering matters, P_ordered != P_shuffled.
    """
    print("=" * 72)
    print("  S6. ORDERED vs SHUFFLED PROCESSING")
    print("=" * 72)
    print()
    print("  For each subset, we compare corrSum with:")
    print("  (a) Standard decreasing order (ORDERED)")
    print(f"  (b) {n_shuffles} random permutations (SHUFFLED)")
    print("  (c) Markov prediction (1/p)")
    print()
    print("  If ordering creates bias, P_ordered != P_shuffled.")
    print()

    hdr = (f"  {'k':>3} {'p':>6} {'C':>8} "
           f"{'P_ord':>10} {'P_shuf':>10} {'1/p':>10} "
           f"{'ord/1p':>8} {'shuf/1p':>8} {'ord/shuf':>9}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    results = []

    for k in k_range_detail:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue

        n_subsets = math.comb(S - 1, k - 1)
        if n_subsets > 100000:
            continue

        for p in prime_factors(d):
            if p < 3:
                continue

            N_ordered_zero = 0
            N_shuffled_zero = 0
            N_shuffled_total = 0
            N_total = 0

            for subset in combinations(range(1, S), k - 1):
                N_total += 1

                # Ordered
                c_ord = horner_chain_ordered(subset, k, p)
                if c_ord == 0:
                    N_ordered_zero += 1

                # Shuffled
                elements = list(subset)
                for _ in range(n_shuffles):
                    perm = elements[:]
                    RNG.shuffle(perm)
                    c_shuf = horner_chain_arbitrary_order(perm, p)
                    N_shuffled_total += 1
                    if c_shuf == 0:
                        N_shuffled_zero += 1

            P_ord = N_ordered_zero / N_total if N_total > 0 else 0
            P_shuf = N_shuffled_zero / N_shuffled_total if N_shuffled_total > 0 else 0
            inv_p = 1.0 / p

            r_ord = P_ord / inv_p
            r_shuf = P_shuf / inv_p
            r_os = P_ord / P_shuf if P_shuf > 0 else float('inf')

            results.append({
                'k': k, 'p': p, 'N_total': N_total,
                'P_ordered': P_ord, 'P_shuffled': P_shuf,
                'ratio_ord_unif': r_ord, 'ratio_shuf_unif': r_shuf,
                'ratio_ord_shuf': r_os,
            })

            print(f"  {k:>3} {p:>6} {N_total:>8} "
                  f"{P_ord:>10.6f} {P_shuf:>10.6f} {inv_p:>10.6f} "
                  f"{r_ord:>8.4f} {r_shuf:>8.4f} {r_os:>9.4f}")

    # Summary
    if results:
        print()
        r_ords = [r['ratio_ord_unif'] for r in results]
        r_shufs = [r['ratio_shuf_unif'] for r in results]
        r_oss = [r['ratio_ord_shuf'] for r in results
                 if r['ratio_ord_shuf'] != float('inf')]
        print(f"  Ordered/uniform : mean={sum(r_ords)/len(r_ords):.4f}, "
              f"range=[{min(r_ords):.4f}, {max(r_ords):.4f}]")
        print(f"  Shuffled/uniform: mean={sum(r_shufs)/len(r_shufs):.4f}, "
              f"range=[{min(r_shufs):.4f}, {max(r_shufs):.4f}]")
        if r_oss:
            print(f"  Ordered/shuffled: mean={sum(r_oss)/len(r_oss):.4f}, "
                  f"range=[{min(r_oss):.4f}, {max(r_oss):.4f}]")
        print()
        mean_os = sum(r_oss) / len(r_oss) if r_oss else 0
        if abs(mean_os - 1.0) < 0.05:
            print("  RESULT: P(corrSum=0) is ROBUST to reordering.")
            print("  The ordering constraint has NO measurable effect.")
        elif mean_os < 1.0:
            print("  RESULT: Ordered chain produces FEWER zeros (aids exclusion).")
        else:
            print("  RESULT: Ordered chain produces MORE zeros (hinders exclusion).")

    print()
    return results


# ============================================================================
# S7. EXHAUSTIVE ALL-PERMUTATIONS (small k only)
# ============================================================================

def exhaustive_all_orders(k_range_tiny):
    """For very small k, enumerate ALL (k-1)! orderings of each subset.

    Gives the EXACT rank of the standard ordering among all permutations.
    """
    print("=" * 72)
    print("  S7. EXHAUSTIVE ALL-PERMUTATIONS COMPARISON")
    print("=" * 72)
    print()
    print("  For small k, we enumerate ALL (k-1)! orderings of each subset")
    print("  and rank the standard (decreasing) ordering by solution count.")
    print()

    hdr = (f"  {'k':>3} {'p':>6} {'(k-1)!':>6} {'C':>8} "
           f"{'N0_ord':>6} {'mean':>8} {'std':>8} "
           f"{'rank':>6} {'%ile':>6}")
    print(hdr)
    print("  " + "-" * (len(hdr) - 2))

    allperm_results = []

    for k in k_range_tiny:
        S = S_of_k(k)
        d = d_of_k(k)
        if d <= 1:
            continue

        km1 = k - 1
        n_perms = math.factorial(km1)
        n_subsets = math.comb(S - 1, km1)

        # Skip if too expensive
        if n_perms * n_subsets > 10000000:
            continue

        for p in prime_factors(d):
            if p < 3:
                continue

            all_perms = list(permutations(range(km1)))

            N_total = 0
            N_ordered_zero = 0
            perm_zero_counts = Counter()

            for subset in combinations(range(1, S), km1):
                N_total += 1

                c_ord = horner_chain_ordered(subset, k, p)
                if c_ord == 0:
                    N_ordered_zero += 1

                elements = list(subset)
                for perm_idx, perm in enumerate(all_perms):
                    reordered = [elements[perm[i]] for i in range(km1)]
                    c = horner_chain_arbitrary_order(reordered, p)
                    if c == 0:
                        perm_zero_counts[perm_idx] += 1

            # Which permutation index is "decreasing"?
            ordered_perm = tuple(range(km1 - 1, -1, -1))
            ordered_perm_idx = all_perms.index(ordered_perm)
            N_ord_from_perms = perm_zero_counts.get(ordered_perm_idx, 0)
            assert N_ord_from_perms == N_ordered_zero

            perm_counts = [perm_zero_counts.get(i, 0) for i in range(len(all_perms))]
            mean_perm = sum(perm_counts) / len(perm_counts)
            var_perm = sum((c - mean_perm)**2 for c in perm_counts) / len(perm_counts)
            std_perm = var_perm ** 0.5

            sorted_counts = sorted(perm_counts)
            rank = sorted_counts.index(N_ordered_zero) + 1
            percentile = rank / len(all_perms) * 100

            allperm_results.append({
                'k': k, 'p': p, 'n_perms': n_perms, 'N_total': N_total,
                'N_ordered_zero': N_ordered_zero,
                'mean_perm': mean_perm, 'std_perm': std_perm,
                'rank': rank, 'percentile': percentile,
            })

            print(f"  {k:>3} {p:>6} {n_perms:>6} {N_total:>8} "
                  f"{N_ordered_zero:>6} {mean_perm:>8.2f} {std_perm:>8.2f} "
                  f"{rank:>6} {percentile:>6.1f}")

    # Summary
    if allperm_results:
        pcts = [a['percentile'] for a in allperm_results]
        print()
        print(f"  Ordered percentile: mean={sum(pcts)/len(pcts):.1f}%, "
              f"min={min(pcts):.1f}%, max={max(pcts):.1f}%")
        avg = sum(pcts) / len(pcts)
        if 35 <= avg <= 65:
            print("  => Standard ordering is NEAR MEDIAN: no systematic bias.")
        elif avg < 35:
            print("  => Standard ordering produces FEWER zeros (aids exclusion).")
        else:
            print("  => Standard ordering produces MORE zeros (hinders exclusion).")

    print()
    return allperm_results


# ============================================================================
# S8. SYNTHESIS
# ============================================================================

def synthesize(geo_results, bias_results, subgroup_data,
               shuffle_results, allperm_results):
    """Synthesize findings to answer the key question."""
    print("=" * 72)
    print("  S8. SYNTHESIS: DOES THE ORDERING CONSTRAINT CREATE BIAS?")
    print("=" * 72)
    print()

    # 1. Geometric structure
    if geo_results:
        coverages = [r['coverage'] for r in geo_results.values()]
        prim_count = sum(1 for r in geo_results.values() if r['primitive_root'])
        total = len(geo_results)
        print("  1. GEOMETRIC STRUCTURE:")
        print(f"     {prim_count}/{total} primes have 2 as primitive root")
        print(f"     Average coverage: {sum(coverages)/len(coverages):.4f}")
        print(f"     Min coverage: {min(coverages):.4f}")
        if min(coverages) >= 0.5:
            print("     => Good coverage: 2^b values span a large subgroup of (Z/pZ)*")
        print()

    # 2. Subgroup <2,3>
    if subgroup_data:
        full_count = sum(1 for s in subgroup_data if s['is_full'])
        total = len(subgroup_data)
        print("  2. SUBGROUP <2,3>:")
        print(f"     <2,3> = (Z/pZ)* for {full_count}/{total} primes")
        if full_count == total:
            print("     => corrSum can reach ALL residues mod p in every case")
            print("     => Subgroup structure DOES NOT restrict corrSum range")
        else:
            non_full = [s for s in subgroup_data if not s['is_full']]
            print(f"     WARNING: {len(non_full)} primes have proper subgroup")
        print()

    # 3. P(corrSum=0) vs 1/p
    if bias_results:
        ratios = [r['ratio'] for r in bias_results]
        mean_r = sum(ratios) / len(ratios)
        # Filtered: exclude under-sampled cases (expected count N/p < 5)
        well_sampled = [r for r in bias_results if r['N'] * r['inv_p'] >= 5]
        ws_ratios = [r['ratio'] for r in well_sampled]
        ws_mean = sum(ws_ratios) / len(ws_ratios) if ws_ratios else mean_r
        print("  3. P(corrSum=0) vs 1/p:")
        print(f"     All cases ({len(ratios)}): mean ratio = {mean_r:.6f}")
        if len(ws_ratios) < len(ratios):
            print(f"     Well-sampled ({len(ws_ratios)}): mean ratio = {ws_mean:.6f}")
            print(f"     (Filtered: excluded {len(ratios)-len(ws_ratios)} cases with N/p < 5)")
        ref_mean = ws_mean  # Use filtered mean for assessment
        if abs(ref_mean - 1.0) < 0.05:
            print("     => P(corrSum=0) is VERY CLOSE to 1/p")
            print("     => The 1/p heuristic is a GOOD approximation")
        elif ref_mean < 1.0:
            print(f"     => P(corrSum=0) is {(1-ref_mean)*100:.1f}% BELOW 1/p (aids exclusion)")
        else:
            print(f"     => P(corrSum=0) is {(ref_mean-1)*100:.1f}% ABOVE 1/p (hinders exclusion)")
        print()

    # 4. Ordered vs shuffled
    if shuffle_results:
        r_os_vals = [r['ratio_ord_shuf'] for r in shuffle_results
                     if r['ratio_ord_shuf'] != float('inf')]
        if r_os_vals:
            mean_os = sum(r_os_vals) / len(r_os_vals)
            print("  4. ORDERED vs SHUFFLED:")
            print(f"     Ordered/Shuffled mean ratio: {mean_os:.4f}")
            if abs(mean_os - 1.0) < 0.05:
                print("     => P(corrSum=0) is ROBUST to element reordering")
            print()

    # 5. Permutation ranking
    if allperm_results:
        pcts = [a['percentile'] for a in allperm_results]
        print("  5. PERMUTATION RANKING:")
        print(f"     Mean percentile: {sum(pcts)/len(pcts):.1f}%")
        if 35 <= sum(pcts)/len(pcts) <= 65:
            print("     => Standard ordering is UNREMARKABLE among all orderings")
        print()

    # Overall verdict
    # Use filtered ratios (N/p >= 5) for the conclusion
    all_ratios = []
    filtered_ratios = []
    if bias_results:
        all_ratios = [r['ratio'] for r in bias_results]
        filtered_ratios = [r['ratio'] for r in bias_results
                          if r['N'] * r['inv_p'] >= 5]

    print("  " + "=" * 60)
    print("  CONCLUSION")
    print("  " + "=" * 60)
    print()

    ref_ratios = filtered_ratios if filtered_ratios else all_ratios
    if ref_ratios:
        mean_r = sum(ref_ratios) / len(ref_ratios)
        if abs(mean_r - 1.0) < 0.05:
            print("  The ordering constraint in the Horner chain does NOT")
            print("  create a measurable systematic bias in P(corrSum=0).")
            print(f"  Mean P(corrSum=0) / (1/p) = {mean_r:.4f}")
            print(f"  ({len(ref_ratios)} well-sampled cases).")
            print("  The 1/p heuristic REMAINS VALID.")
            print()
            print("  IMPORTANT NEGATIVE RESULT:")
            print("  The ordering structure does NOT provide additional")
            print("  obstruction power beyond the Markov model (1/p).")
            print()
            print("  Obstruction to nontrivial cycles must come from:")
            print("  (a) CRT product over multiple primes p | d(k)")
            print("  (b) Multiplicative structure of d(k) itself")
            print("  (c) Without-replacement correlations")
            print("  (d) Structural number-theoretic constraints (e.g., 2-adic)")
            print("  NOT from the ordering of exponents in the Horner chain.")
        elif mean_r < 1.0:
            print("  The ordering constraint creates a MILD NEGATIVE bias:")
            print(f"  P(corrSum=0) / (1/p) = {mean_r:.4f} on average")
            print(f"  ({len(ref_ratios)} well-sampled cases).")
            print()
            if abs(mean_r - 1.0) < 0.10:
                print("  However, the bias is SMALL (<10%) and not statistically")
                print("  significant. For practical purposes, the 1/p heuristic")
                print("  remains a reasonable approximation.")
                print()
                print("  The slight deficit may aid cycle exclusion but does not")
                print("  constitute a standalone obstruction mechanism.")
            else:
                print("  This STRENGTHENS the non-existence argument.")
            print()
            print("  Obstruction to nontrivial cycles must primarily come from:")
            print("  (a) CRT product over multiple primes p | d(k)")
            print("  (b) Multiplicative structure of d(k) itself")
            print("  (c) Without-replacement correlations")
            print("  (d) Structural number-theoretic constraints (e.g., 2-adic)")
        else:
            print("  The ordering constraint creates a POSITIVE bias:")
            print(f"  P(corrSum=0) / (1/p) = {mean_r:.4f} on average.")
            print("  This WEAKENS the non-existence argument.")

    print()


# ============================================================================
# SHA256 FINGERPRINT
# ============================================================================

def compute_fingerprint(bias_results, subgroup_data, shuffle_results, allperm_results):
    """Compute SHA256 fingerprint of key numerical results."""
    data = []

    if bias_results:
        for r in sorted(bias_results, key=lambda x: (x['k'], x['p'])):
            data.append(('bias', r['k'], r['p'], r['sol_count'], r['N'],
                         round(r['P_zero'], 12), r['method']))

    if subgroup_data:
        for s in sorted(subgroup_data, key=lambda x: (x['k'], x['p'])):
            data.append(('subgroup', s['k'], s['p'], s['ord_2'], s['ord_3'],
                         s['size_23'], s['is_full']))

    if shuffle_results:
        for r in sorted(shuffle_results, key=lambda x: (x['k'], x['p'])):
            data.append(('shuffle', r['k'], r['p'],
                         round(r['P_ordered'], 12),
                         round(r['P_shuffled'], 12)))

    if allperm_results:
        for a in sorted(allperm_results, key=lambda x: (x['k'], x['p'])):
            data.append(('allperm', a['k'], a['p'],
                         a['N_ordered_zero'], a['rank'],
                         round(a['mean_perm'], 8),
                         round(a['percentile'], 4)))

    sig = json.dumps(data, sort_keys=True)
    return hashlib.sha256(sig.encode()).hexdigest()


# ============================================================================
# MAIN
# ============================================================================

def main():
    t_start = time.time()

    print()
    print("=" * 72)
    print("  r2_ordering_constraint.py")
    print("  Ordering Constraint & Geometric Structure Analysis")
    print("  Collatz Cycle Non-Existence, k = 7..20")
    print("=" * 72)
    print()

    # Self-tests
    if not self_test():
        print("  ABORTING: self-tests failed.")
        return 1

    # S2: Geometric structure for k = 7..20
    k_range_full = range(7, 21)
    geo_results = analyze_geometric_structure(k_range_full)

    # S3: P(corrSum=0) vs 1/p
    # Exact for k=7..12 (feasible), sampling for k=13..20
    k_range_exact = range(7, 13)
    k_range_sample = range(13, 21)
    bias_results = analyze_ordering_bias(k_range_exact, k_range_sample,
                                         n_samples=200000)

    # S4: Consecutive ratio analysis (detail for k=7..9)
    analyze_consecutive_ratios(range(7, 10))

    # S5: Subgroup structure for k=7..20
    subgroup_data = analyze_subgroup_structure(k_range_full)

    # S6: Ordered vs shuffled (feasible k only)
    shuffle_results = compare_ordered_vs_shuffled(range(7, 11), n_shuffles=50)

    # S7: All-permutations (very small k only)
    allperm_results = exhaustive_all_orders(range(3, 8))

    # S8: Synthesis
    synthesize(geo_results, bias_results, subgroup_data,
               shuffle_results, allperm_results)

    # SHA256 fingerprint
    sha = compute_fingerprint(bias_results, subgroup_data,
                              shuffle_results, allperm_results)

    elapsed = time.time() - t_start
    print(f"  SHA256 fingerprint: {sha}")
    print(f"  Computation time: {elapsed:.1f}s")
    print(f"  Python: {sys.version.split()[0]}")
    print()
    print("=" * 72)
    print("  END OF ANALYSIS")
    print("=" * 72)

    return 0


if __name__ == "__main__":
    sys.exit(main())
