"""
Formalizer — Lean 4 Code Generation

Takes typed Hypotheses from the Conjecturer and generates compilable
Lean 4 code. Knows the Lean 4 syntax and the CorrSumAvoidance library.
"""

import math
from typing import List
from syracuse_jepa.pipeline.conjecturer import Hypothesis, HypothesisType


def generate_s_table_entry(k: int) -> str:
    """Generate one line of the S_table match."""
    S = math.ceil(k * math.log2(3))
    return f"  | {k} => {S}"


def generate_basic_lean(k_max: int) -> str:
    """Generate CorrSumAvoidance/Basic.lean with S_table up to k_max."""
    s_entries = "\n".join(generate_s_table_entry(k) for k in range(0, k_max + 1))

    return f"""/-
  CorrSum Avoidance — Core Definitions
  AUTO-GENERATED by Syracuse-JEPA Pipeline Formalizer

  corrSum(A, k) = Σᵢ 3^{{k-1-i}} · 2^{{Aᵢ}}
  S(k) = ⌈k · log₂(3)⌉
  d(k) = 2^{{S(k)}} - 3^k
-/

namespace CorrSumAvoidance

/-- corrSum helper -/
def corrSumGo : List Nat → Nat → Nat
  | [], _ => 0
  | a :: rest, pow3 => 3 ^ pow3 * 2 ^ a + corrSumGo rest (pow3 - 1)

/-- corrSum(A, k) = Σᵢ₌₀^{{k-1}} 3^{{k-1-i}} · 2^{{Aᵢ}} -/
def corrSum (A : List Nat) (k : Nat) : Nat :=
  corrSumGo A (k - 1)

/-- Enumerate monotone compositions of `total` into `parts` parts ≥ `minVal` -/
def enumMonotone : Nat → Nat → Nat → List (List Nat)
  | 0, total, _ => if total == 0 then [[]] else []
  | parts + 1, total, minVal =>
    if parts == 0 then
      if total ≥ minVal then [[total]] else []
    else
      let k := parts + 1
      let maxFirst := total / k
      if maxFirst < minVal then []
      else
        ((List.range (maxFirst - minVal + 1)).map fun i =>
          let v := i + minVal
          (enumMonotone parts (total - v) v).map (v :: ·)).flatten

/-- S(k) = ⌈k · log₂(3)⌉ -/
def S_table : Nat → Nat
{s_entries}
  | _ => 0

/-- d(k) = 2^{{S(k)}} - 3^k -/
def d_val (k : Nat) : Nat :=
  2 ^ (S_table k) - 3 ^ k

/-- Check N₀ = 0: all compositions have corrSum not divisible by d -/
def checkAvoidance (k : Nat) : Bool :=
  let s := S_table k
  let d := d_val k
  if d == 0 then false
  else
    (enumMonotone k s 0).all fun A => corrSum A k % d != 0

/-- Check a specific composition is a phantom -/
def checkPhantom (A : List Nat) (k : Nat) : Bool :=
  let d := d_val k
  d != 0 && corrSum A k % d == 0

end CorrSumAvoidance
"""


def generate_theorem(h: Hypothesis) -> str:
    """Generate a single Lean 4 theorem from a Hypothesis."""
    if h.type == HypothesisType.AVOIDANCE:
        S = math.ceil(h.k * math.log2(3))
        d = (1 << S) - 3**h.k
        return (
            f"/-- k={h.k}: S={S}, d={d}. {h.description} -/\n"
            f"theorem {h.lean_name} : checkAvoidance {h.k} = true := by native_decide"
        )

    elif h.type == HypothesisType.AVOIDANCE_FAILS:
        return (
            f"/-- {h.description} -/\n"
            f"theorem {h.lean_name} : checkAvoidance {h.k} = false := by native_decide"
        )

    elif h.type == HypothesisType.PHANTOM:
        comp_str = ", ".join(str(x) for x in h.composition)
        return (
            f"/-- {h.description} -/\n"
            f"theorem {h.lean_name} : checkPhantom [{comp_str}] {h.k} = true := "
            f"by native_decide"
        )

    elif h.type == HypothesisType.EXACT_VALUE and h.composition is not None:
        comp_str = ", ".join(str(x) for x in h.composition)
        return (
            f"/-- {h.description} -/\n"
            f"theorem {h.lean_name} : "
            f"corrSum [{comp_str}] {h.k} = {h.expected_value} := by native_decide"
        )

    elif h.type == HypothesisType.DIVISIBILITY:
        comp_str = ", ".join(str(x) for x in h.composition)
        m = h.expected_value
        return (
            f"/-- {h.description} -/\n"
            f"theorem {h.lean_name} : "
            f"corrSum [{comp_str}] {h.k} = {m} * d_val {h.k} := by native_decide"
        )

    elif h.type == HypothesisType.CLOSED_FORM:
        comp_str = ", ".join(str(x) for x in h.composition)
        v = h.formula_params['v']
        k = h.k
        r = h.formula_params['r']
        if r == 0:
            formula = f"2 ^ {v} * ((3 ^ {k} - 1) / 2)"
        else:
            formula = f"2 ^ {v} * ((3 ^ {k} - 1) / 2 + (3 ^ {r} - 1) / 2)"
        return (
            f"/-- {h.description} -/\n"
            f"theorem {h.lean_name} :\n"
            f"    corrSum [{comp_str}] {k} = {formula} := by\n"
            f"  native_decide"
        )

    return f"-- TODO: {h.type.value} for k={h.k}"


def generate_theorems_lean(hypotheses: List[Hypothesis]) -> str:
    """Generate the complete Theorems.lean file from hypotheses."""
    # Group by type
    avoidance = [h for h in hypotheses if h.type == HypothesisType.AVOIDANCE]
    failures = [h for h in hypotheses if h.type == HypothesisType.AVOIDANCE_FAILS]
    phantoms = [h for h in hypotheses if h.type == HypothesisType.PHANTOM]
    closed = [h for h in hypotheses if h.type == HypothesisType.CLOSED_FORM]
    exact = [h for h in hypotheses if h.type == HypothesisType.EXACT_VALUE]
    divs = [h for h in hypotheses if h.type == HypothesisType.DIVISIBILITY]

    k_avoidance = [h.k for h in avoidance]
    k_range = f"{min(k_avoidance)}..{max(k_avoidance)}" if k_avoidance else "none"
    k_excluded = [h.k for h in failures]

    sections = []

    # Header
    sections.append(f"""/-
  CorrSum Avoidance Theorems — AUTO-GENERATED & Verified by native_decide

  MAIN RESULT (Residue Avoidance Lemma):
  For k ∈ {{{k_range}}} \\ {{{', '.join(str(x) for x in k_excluded)}}},
  no monotone composition A of S(k) into k parts satisfies
    corrSum(A, k) ≡ 0 (mod d(k))

  Generated by Syracuse-JEPA Pipeline.
  {len(avoidance)} avoidance theorems, {len(phantoms)} phantoms,
  {len(closed)} closed forms, {len(exact)} exact values.
-/

import CorrSumAvoidance.Basic

open CorrSumAvoidance""")

    # Part 1: Avoidance
    if avoidance:
        sections.append("\n-- ═══════════════════════════════════════════════════════════════")
        sections.append("--  PART 1: Residue Avoidance — N₀(d(k)) = 0")
        sections.append("-- ═══════════════════════════════════════════════════════════════\n")
        for h in avoidance:
            sections.append(generate_theorem(h))
            sections.append("")

    # Part 2: Failures (phantoms)
    if failures or phantoms:
        sections.append("-- ═══════════════════════════════════════════════════════════════")
        sections.append("--  PART 2: Exceptions — N₀ > 0")
        sections.append("-- ═══════════════════════════════════════════════════════════════\n")
        for h in failures:
            sections.append(generate_theorem(h))
            sections.append("")
        for h in phantoms:
            sections.append(generate_theorem(h))
            sections.append("")

    # Part 3: Exact values & divisibility
    if exact or divs:
        sections.append("-- ═══════════════════════════════════════════════════════════════")
        sections.append("--  PART 3: Exact values & divisibility")
        sections.append("-- ═══════════════════════════════════════════════════════════════\n")
        for h in exact:
            sections.append(generate_theorem(h))
            sections.append("")
        for h in divs:
            sections.append(generate_theorem(h))
            sections.append("")

    # Part 4: Closed forms
    if closed:
        sections.append("-- ═══════════════════════════════════════════════════════════════")
        sections.append("--  PART 4: Almost-flat closed form verification")
        sections.append("-- ═══════════════════════════════════════════════════════════════\n")
        # Only emit a sample (every 5th k) to keep compile time reasonable
        sample = closed[::5] if len(closed) > 10 else closed
        for h in sample:
            sections.append(generate_theorem(h))
            sections.append("")

    return "\n".join(sections)


def formalize(hypotheses: List[Hypothesis], lean_dir: str) -> dict:
    """
    Generate all Lean 4 files from hypotheses.
    Returns dict with file paths and content.
    """
    print("=" * 70)
    print("  FORMALIZER — Generating Lean 4 code")
    print("=" * 70)

    # Determine k_max from hypotheses
    all_k = [h.k for h in hypotheses if h.k is not None]
    k_max = max(all_k) if all_k else 40

    basic_content = generate_basic_lean(k_max)
    theorems_content = generate_theorems_lean(hypotheses)

    files = {
        f"{lean_dir}/CorrSumAvoidance/Basic.lean": basic_content,
        f"{lean_dir}/CorrSumAvoidance/Theorems.lean": theorems_content,
    }

    n_theorems = sum(1 for h in hypotheses
                     if h.type in (HypothesisType.AVOIDANCE, HypothesisType.AVOIDANCE_FAILS,
                                   HypothesisType.PHANTOM, HypothesisType.CLOSED_FORM,
                                   HypothesisType.EXACT_VALUE, HypothesisType.DIVISIBILITY))
    print(f"  Generated {n_theorems} theorems for k up to {k_max}")
    print(f"  Files: {list(files.keys())}")

    return files
