#!/usr/bin/env python3
"""
HYPOTHESIS EVOLUTION — Genetic Algorithm on Proof Lemmas
==========================================================

Inspired by FunSearch (Romera-Paredes et al., 2024):
- Population of HYPOTHESES (lemma statements)
- FITNESS = numerical verification score (0-1)
- MUTATION = modify one aspect of a hypothesis
- CROSSOVER = combine two partial arguments
- SELECTION = keep best-scoring hypotheses

Each hypothesis is a FUNCTION that takes (k, σ, corrSum, d) and returns
a PREDICTION of whether corrSum ≡ 0 mod d. If the function always
returns False for non-zero cases and True for zero cases: it's a proof.

The evolution searches for the RIGHT discriminating function.
"""

import sys, os, json, random, time
from math import ceil, log2, comb, gcd
from itertools import combinations
from copy import deepcopy

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from syracuse_jepa.pipeline.cumulative_generator import (
    compute_S, compute_d, corrsum_cumulative,
    enumerate_cumulative_sequences, count_cumulative_sequences,
)

# ══════════════════════════════════════════════════════════════
# HYPOTHESIS REPRESENTATION
# ══════════════════════════════════════════════════════════════

class Hypothesis:
    """A hypothesis about WHY corrSum ≢ 0 mod d."""
    def __init__(self, name, predicate, description):
        self.name = name
        self.predicate = predicate  # (k, S, d, sigma, cs) -> bool (True = predicts non-divisibility)
        self.description = description
        self.fitness = 0.0
        self.generation = 0

    def test(self, k, S, d, sigma, cs):
        try:
            return self.predicate(k, S, d, sigma, cs)
        except:
            return None  # Error = bad hypothesis

    def __repr__(self):
        return f"H({self.name}, fitness={self.fitness:.4f})"


# ══════════════════════════════════════════════════════════════
# INITIAL POPULATION — Seed hypotheses from our discoveries
# ══════════════════════════════════════════════════════════════

def create_initial_population():
    """Create initial hypothesis population from known insights."""
    population = []

    # H1: corrSum is always odd, d is always odd → corrSum/d could be integer
    # But corrSum mod 2 = 1 and d mod 2 = 1, so no parity block.
    # This is a NEGATIVE result but useful as baseline.

    # H2: gcd(corrSum, d) < d (weaker than coprime)
    population.append(Hypothesis(
        "gcd_lt_d",
        lambda k, S, d, sigma, cs: gcd(cs, d) < d,
        "gcd(corrSum, d) < d always"
    ))

    # H3: corrSum mod d > sqrt(d)
    population.append(Hypothesis(
        "mod_gt_sqrt",
        lambda k, S, d, sigma, cs: (cs % d) > int(d**0.5),
        "corrSum mod d > √d"
    ))

    # H4: The δ-sequence sorted property blocks divisibility
    population.append(Hypothesis(
        "ordering_blocks",
        lambda k, S, d, sigma, cs: True,  # Always true by definition (tautology)
        "Ordered δ always avoids target (the tautological hypothesis)"
    ))

    # H5: corrSum ≡ 3^{k-1} mod 3 (since other terms are div by 3 at various levels)
    population.append(Hypothesis(
        "mod3_structure",
        lambda k, S, d, sigma, cs: cs % 3 != 0,  # corrSum never div by 3
        "v₃(corrSum) = 0 always (last term 2^{σ_{k-1}} not div by 3)"
    ))

    # H6: corrSum/d rounded is always even (near-miss observation)
    population.append(Hypothesis(
        "nearest_quotient_even",
        lambda k, S, d, sigma, cs: round(cs / d) % 2 == 0,
        "Nearest integer to corrSum/d is even (cycle needs odd)"
    ))

    # H7: REST' + 1 is in the group generated by ρ
    population.append(Hypothesis(
        "rest_in_rho_group",
        lambda k, S, d, sigma, cs: True,  # Placeholder
        "REST'+1 lies in <ρ> where ρ = 2/3 mod d"
    ))

    # H8: The polynomial Q_δ(ρ) has specific algebraic structure
    population.append(Hypothesis(
        "poly_structure",
        lambda k, S, d, sigma, cs: cs % d != 0,  # The TARGET hypothesis
        "Sorting polynomial Q_δ evaluated at ρ is never 0"
    ))

    # H9: corrSum mod d is always a quadratic residue
    population.append(Hypothesis(
        "quadratic_residue",
        lambda k, S, d, sigma, cs: True,  # Placeholder (need Legendre symbol)
        "corrSum mod d is always a QR when d is prime"
    ))

    # H10: First and last terms of corrSum constrain the residue
    population.append(Hypothesis(
        "endpoint_constraint",
        lambda k, S, d, sigma, cs: (pow(3, k-1, d) + pow(2, sigma[-1], d)) % d != 0,
        "3^{k-1} + 2^{σ_{k-1}} ≢ 0 mod d (endpoint sum)"
    ))

    return population


# ══════════════════════════════════════════════════════════════
# FITNESS EVALUATION
# ══════════════════════════════════════════════════════════════

def evaluate_fitness(hyp, test_data):
    """
    Fitness = fraction of correct predictions.
    A hypothesis predicts whether corrSum ≢ 0 mod d.
    Since N₀ = 0 for all tested k: correct prediction = True (always non-div).
    Fitness = 1.0 if hypothesis always returns True for all test cases.
    """
    correct = 0
    total = 0
    errors = 0

    for k, data in test_data.items():
        for sigma, cs in data['samples']:
            result = hyp.test(k, data['S'], data['d'], sigma, cs)
            if result is None:
                errors += 1
            elif result == True:
                correct += 1  # Correctly predicts non-divisibility
            # result == False would be a wrong prediction (since N₀=0)
            total += 1

    hyp.fitness = correct / total if total > 0 else 0
    return hyp.fitness


def prepare_test_data(k_max=10):
    """Prepare test data for fitness evaluation."""
    data = {}
    for k in range(3, k_max + 1):
        S = compute_S(k)
        d = compute_d(k)
        if d <= 0: continue
        C = count_cumulative_sequences(k, S)
        if C > 50000: continue

        samples = []
        for sigma in enumerate_cumulative_sequences(k, S):
            cs = corrsum_cumulative(sigma, k)
            samples.append((sigma, cs))

        data[k] = {'S': S, 'd': d, 'C': C, 'samples': samples}

    return data


# ══════════════════════════════════════════════════════════════
# MUTATION OPERATORS
# ══════════════════════════════════════════════════════════════

def mutate_threshold(hyp):
    """Mutate a threshold-based hypothesis."""
    # Example: change sqrt(d) to d^0.3 or d^0.7
    exp = random.choice([0.2, 0.3, 0.4, 0.6, 0.7, 0.8])
    new_name = f"mod_gt_d^{exp}"
    return Hypothesis(
        new_name,
        lambda k, S, d, sigma, cs, e=exp: (cs % d) > int(d**e),
        f"corrSum mod d > d^{exp}"
    )


def mutate_modular(hyp):
    """Create a modular-arithmetic hypothesis."""
    m = random.choice([2, 3, 4, 5, 6, 7, 8, 9])
    target = random.randint(0, m-1)
    return Hypothesis(
        f"cs_mod_{m}_is_{target}",
        lambda k, S, d, sigma, cs, m=m, t=target: cs % m == t,
        f"corrSum ≡ {target} mod {m}"
    )


def mutate_gcd_variant(hyp):
    """Variants of gcd-based hypotheses."""
    variant = random.choice(['coprime_to_smallest_factor', 'gcd_is_power_of_2',
                             'gcd_divides_3k_minus_1'])
    if variant == 'coprime_to_smallest_factor':
        return Hypothesis(
            "coprime_smallest_factor",
            lambda k, S, d, sigma, cs: gcd(cs, d) == 1 or gcd(cs, d) < d,
            "gcd(corrSum, d) is a proper divisor"
        )
    elif variant == 'gcd_is_power_of_2':
        return Hypothesis(
            "gcd_not_full_d",
            lambda k, S, d, sigma, cs: gcd(cs, d) != d,
            "gcd(corrSum, d) ≠ d"
        )
    else:
        return Hypothesis(
            "gcd_divides_3k_minus_1",
            lambda k, S, d, sigma, cs: gcd(cs, d) in [1] or gcd(cs, 3**k - 1) < d,
            "gcd(corrSum, 3^k-1) < d"
        )


def mutate(hyp):
    """Apply a random mutation."""
    mutators = [mutate_threshold, mutate_modular, mutate_gcd_variant]
    return random.choice(mutators)(hyp)


# ══════════════════════════════════════════════════════════════
# EVOLUTION LOOP
# ══════════════════════════════════════════════════════════════

def evolve(n_generations=20, population_size=15):
    """Run the genetic algorithm."""
    print("HYPOTHESIS EVOLUTION ENGINE")
    print("=" * 60)

    # Prepare test data
    test_data = prepare_test_data(k_max=10)
    total_samples = sum(d['C'] for d in test_data.values())
    print(f"Test data: {len(test_data)} k-values, {total_samples} samples\n")

    # Initialize population
    population = create_initial_population()

    # Evaluate initial fitness
    for hyp in population:
        evaluate_fitness(hyp, test_data)

    best_ever = max(population, key=lambda h: h.fitness)

    for gen in range(n_generations):
        # Sort by fitness
        population.sort(key=lambda h: h.fitness, reverse=True)

        # Report
        best = population[0]
        mean_fit = sum(h.fitness for h in population) / len(population)
        print(f"Gen {gen:3d}: best={best.fitness:.4f} ({best.name}), "
              f"mean={mean_fit:.4f}, pop={len(population)}")

        if best.fitness > best_ever.fitness:
            best_ever = deepcopy(best)

        if best.fitness >= 1.0:
            print(f"\n★★★ PERFECT HYPOTHESIS FOUND: {best.name}")
            print(f"    {best.description}")
            break

        # Selection: keep top half
        survivors = population[:population_size // 2]

        # Mutation: create offspring
        offspring = []
        for _ in range(population_size - len(survivors)):
            parent = random.choice(survivors)
            child = mutate(parent)
            child.generation = gen + 1
            evaluate_fitness(child, test_data)
            offspring.append(child)

        population = survivors + offspring

        # Ensure population size
        while len(population) < population_size:
            new = mutate(random.choice(population))
            new.generation = gen + 1
            evaluate_fitness(new, test_data)
            population.append(new)

    # Final report
    population.sort(key=lambda h: h.fitness, reverse=True)
    print(f"\n{'='*60}")
    print(f"EVOLUTION COMPLETE — Best ever: {best_ever.name} ({best_ever.fitness:.4f})")
    print(f"Description: {best_ever.description}")

    print(f"\nTop 5 hypotheses:")
    for h in population[:5]:
        print(f"  [{h.fitness:.4f}] {h.name}: {h.description[:70]}")

    return population


if __name__ == '__main__':
    random.seed(42)
    population = evolve(n_generations=30, population_size=20)
