#!/usr/bin/env python3
"""
SUBGROUP SEARCH — Find universal algebraic containment for REST'+1
====================================================================

For k=3,5: REST'+1 ∈ <2> mod d (proved N₀=0).
For k=4,6+: REST'+1 ∉ <2> always. Need DIFFERENT structure.

IDEA: Instead of a SINGLE subgroup, maybe REST'+1 avoids 0 because
it's always a UNIT (element of (Z/dZ)*). We showed gcd(REST'+1, d) = 1
for k=3,4,5. But for k=6+: gcd can be >1 (5, 59 factors appear).

NEW IDEA: REST'+1 might always be NONZERO because of a VALUATION argument.
For each p | d: v_p(REST'+1) < v_p(d). If this holds for ALL p | d,
then d ∤ (REST'+1), hence REST' ≠ -1, hence corrSum ≢ 0 mod d.

This splits the problem PRIME BY PRIME — but with a twist:
we need v_p(REST'+1) < v_p(d), which is DIFFERENT from N₀(p)=0.
"""

import sys, os
from math import ceil, log2, comb, gcd
from itertools import combinations
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from syracuse_jepa.pipeline.cumulative_generator import (
    compute_S, compute_d, corrsum_cumulative,
    enumerate_cumulative_sequences, count_cumulative_sequences,
)


def factorize(n):
    factors = {}
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors[d] = factors.get(d, 0) + 1
            n //= d
        d += 1
    if n > 1:
        factors[n] = 1
    return factors


def analyze_valuation_obstruction(k_max=12):
    """
    For each k and each p | d:
    Check if v_p(corrSum) < v_p(d) for ALL cumulative sequences.
    If yes for ALL primes simultaneously, N₀ = 0 is proved.

    This is DIFFERENT from checking N₀(p) = 0:
    - N₀(p) = 0 means corrSum ≢ 0 mod p (for ALL sequences)
    - v_p(corrSum) < v_p(d) means corrSum is divisible by p less times than d
    - For v_p(d) = 1: these are the same
    - For v_p(d) > 1: the valuation condition is WEAKER (easier to satisfy)
    """
    print("VALUATION OBSTRUCTION ANALYSIS")
    print("=" * 70)
    print("For each p|d: check max v_p(corrSum) < v_p(d) over all sequences\n")

    results = []

    for k in range(3, k_max + 1):
        S = compute_S(k)
        d = compute_d(k)
        if d <= 0: continue
        C = count_cumulative_sequences(k, S)
        if C > 500000: continue

        factors = factorize(d)
        if not factors: continue

        # For each sequence, compute corrSum and its p-valuations
        all_ok = True
        per_prime = {}

        for p, vd in factors.items():
            max_vp = 0
            for sigma in enumerate_cumulative_sequences(k, S):
                cs = corrsum_cumulative(sigma, k)
                v = 0
                x = cs
                while x > 0 and x % p == 0:
                    v += 1
                    x //= p
                if v > max_vp:
                    max_vp = v

            blocks = max_vp < vd
            per_prime[p] = {'vd': vd, 'max_vp_corrsum': max_vp, 'blocks': blocks}
            if not blocks:
                all_ok = False

        # Does SOME prime block? (CRT: we need AT LEAST ONE)
        any_blocks = any(info['blocks'] for info in per_prime.values())

        status = "✓ PROVED" if any_blocks else "✗ OPEN"
        print(f"k={k}, d={d}={' · '.join(f'{p}^{e}' for p,e in factors.items())}:")
        for p, info in per_prime.items():
            mark = "✓" if info['blocks'] else "✗"
            print(f"  {mark} p={p}: v_p(d)={info['vd']}, max v_p(corrSum)={info['max_vp_corrsum']}")
        print(f"  → {status} (need at least one ✓)")

        results.append({
            'k': k, 'd': d, 'any_blocks': any_blocks, 'all_ok': all_ok,
            'per_prime': per_prime,
        })

    # Summary
    print("\n" + "=" * 70)
    proved = [r for r in results if r['any_blocks']]
    open_cases = [r for r in results if not r['any_blocks']]
    print(f"Proved by valuation: {len(proved)}/{len(results)}")
    if open_cases:
        print(f"Open cases: k = {[r['k'] for r in open_cases]}")
    else:
        print("ALL cases proved by valuation obstruction!")

    return results


def search_multiplicative_structure(k_max=12):
    """
    For each k, check if corrSum mod d is always in a specific
    MULTIPLICATIVE structure that excludes 0.

    Candidates:
    1. <2> = subgroup generated by 2 in (Z/dZ)*
    2. <3> = subgroup generated by 3
    3. <2,3> = subgroup generated by 2 and 3
    4. Coset of a subgroup
    """
    print("\n═══ MULTIPLICATIVE STRUCTURE SEARCH ═══")

    for k in range(3, k_max + 1):
        S = compute_S(k)
        d = compute_d(k)
        if d <= 0: continue
        C = count_cumulative_sequences(k, S)
        if C > 200000: continue

        # Compute all corrSum mod d
        residues = set()
        for sigma in enumerate_cumulative_sequences(k, S):
            cs = corrsum_cumulative(sigma, k)
            residues.add(cs % d)

        # Generate <2> mod d
        gen2 = set()
        x = 1
        for _ in range(d):
            gen2.add(x)
            x = (x * 2) % d
            if x == 1: break

        # Generate <3> mod d
        gen3 = set()
        x = 1
        for _ in range(d):
            gen3.add(x)
            x = (x * 3) % d
            if x == 1: break

        # Generate <2,3> mod d (= <6> if 6 is a generator)
        gen23 = set()
        frontier = {1}
        visited = set()
        while frontier:
            x = frontier.pop()
            if x in visited: continue
            visited.add(x)
            gen23.add(x)
            frontier.add((x * 2) % d)
            frontier.add((x * 3) % d)

        # Check containment
        in_gen2 = residues <= gen2
        in_gen3 = residues <= gen3
        in_gen23 = residues <= gen23

        # <2,3> is a subgroup of (Z/dZ)* which NEVER contains 0.
        # If residues ⊂ <2,3>, then 0 ∉ residues!

        print(f"\n  k={k}, d={d}, |residues|={len(residues)}")
        print(f"    |<2>|={len(gen2)}, |<3>|={len(gen3)}, |<2,3>|={len(gen23)}")
        print(f"    residues ⊂ <2>: {in_gen2}")
        print(f"    residues ⊂ <3>: {in_gen3}")
        print(f"    residues ⊂ <2,3>: {in_gen23}")

        if in_gen23:
            print(f"    ★★★ corrSum mod d ALWAYS in <2,3>! Since 0 ∉ <2,3>, N₀=0 PROVED!")

        # Even if not all in <2,3>, check: how many are?
        in_count = sum(1 for r in residues if r in gen23)
        print(f"    {in_count}/{len(residues)} residues in <2,3> ({in_count/len(residues):.3f})")

        # Check if the COMPLEMENT (residues NOT in <2,3>) are still nonzero
        complement = residues - gen23
        if complement and 0 not in complement:
            print(f"    Complement residues: all nonzero ✓ ({len(complement)} values)")


if __name__ == '__main__':
    analyze_valuation_obstruction()
    search_multiplicative_structure()
